services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/mikesir87/labspace-agentic-compose

  workspace:
    ports: !override
      - 6274:6274
      - 6277:6277
      - 8085:8085
      
    environment:
      OPENAI_BASE_URL: http://model-runner.docker.internal/engines/v1
      OPENAI_API_KEY: not-required
      OPENAI_MODEL: ai/gemma3:4B-Q4_K_M

      # Settings for the MCP Inspector and MCP Gateway
      HOST: 0.0.0.0
      DANGEROUSLY_OMIT_AUTH: "true"
      MCP_AUTO_OPEN_ENABLED: "false"
      DOCKER_MCP_IN_CONTAINER: "1"

  visual-chatbot:
    image: mikesir87/visual-chatbot
    use_api_socket: true
    ports:
      - 3050:3000
    models:
      gemma3:
        endpoint_var: OPENAI_BASE_URL
        model_var: OPENAI_MODEL

models:
  gemma3:
    model: ai/gemma3:4B-Q4_K_M
